name: hanjul_front
description: Hanjul.

publish_to: 'none'

version: 0.0.5+5

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  graphql_flutter: ^5.0.0-nullsafety.2
  jwt_decoder: ^2.0.1
  flutter_secure_storage: ^4.2.0
  flutter_dotenv: ^4.0.0-nullsafety.1
  graphql: ^5.0.0-nullsafety.4
  universal_html: ^2.0.8
  get:
  font_awesome_flutter: ^9.1.0
  settings_ui: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - dotenv
    - assets/logo.png

  fonts:
    - family: Nanum Myeongjo
      fonts:
        - asset: fonts/NanumMyeongjo-Regular.ttf
        - asset: fonts/NanumMyeongjo-Bold.ttf
          weight: 700
